import type { Metadata } from "next";
import localFont from "next/font/local";

import Layout from "../_components/Layout";

import LazyMotionProvider from "@/components/LazyMotionProvider";
import TanstackQueryClientProvider from "@/components/TanstackQueryClientProvider";

import "../globals.css";

const pretendard = localFont({
  src: "../PretendardVariable.woff2",
  display: "swap",
  weight: "45 920",
  variable: "--font-pretendard",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <TanstackQueryClientProvider>
        <LazyMotionProvider>
          <body className={`${pretendard.variable} font-sans antialiased`}>
            <Layout>{children}</Layout>
          </body>
        </LazyMotionProvider>
      </TanstackQueryClientProvider>
    </html>
  );
}
